In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
reshape=arr.reshape(2,5)
print(reshape)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
arr=np.array([1,2,3,4,6,7,5,8,9,10,11,12])
reshape=arr.reshape(1,2,6)
print(reshape)

[[[ 1  2  3  4  6  7]
  [ 5  8  9 10 11 12]]]


In [7]:
try:
    invalid=arr.reshape(4,4)
    print(invalid)
except ValueError as e:
    print("Error:", e)

Error: cannot reshape array of size 12 into shape (4,4)


In [8]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
flat=arr.flatten()
print(flat)

[1 2 3 4 5 6 7 8 9]


In [11]:
ravel=arr.ravel()
print(ravel)
flat[0]=100
ravel[1]=200
print(flat)
print(ravel)

[1 2 3 4 5 6 7 8 9]
[100 200   3   4   5   6   7   8   9]
[100 200   3   4   5   6   7   8   9]


In [12]:
arr=np.array([[1,2],[3,4,]])
transpose=arr.T
print(transpose)

[[1 3]
 [2 4]]


In [13]:
print("originalshape",arr.shape)
print("rows",arr.shape[0])
print("columns",arr.shape[1]) 
print("transpose shape",transpose.shape)
print("transpose rows",transpose.shape[0])
print("transpose columns",transpose.shape[1])

originalshape (2, 2)
rows 2
columns 2
transpose shape (2, 2)
transpose rows 2
transpose columns 2


In [15]:
a=np.array([1,2])
b=np.array([3,4])
print(np.vstack((a,b)))
print(np.hstack((a,b)))
print(np.concatenate((a,b)))

[[1 2]
 [3 4]]
[1 2 3 4]
[1 2 3 4]


In [ ]:
arr=np.array([1,2,3,4,])
print(np.split(arr,2))


[array([1, 2]), array([3, 4])]


ZeroDivisionError: integer modulo by zero