In [2]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)
print(a*b)
print(a/b)


[ 6  8 10 12]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [4]:
print(a+2)
print(a*2)
print(b-4)

[3 4 5 6]
[2 4 6 8]
[1 2 3 4]


In [6]:
print(np.sqrt(b))
print(np.log(a))
print(np.ceil(a))
print(np.floor(b))

[2.23606798 2.44948974 2.64575131 2.82842712]
[0.         0.69314718 1.09861229 1.38629436]
[1 2 3 4]
[5 6 7 8]


In [7]:
print(np.sum(a))
print(np.mean(b))
print(np.max(a))
print(np.min(b))

10
6.5
4
5


In [8]:
arr=np.array([[1,2],[3,4]])
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

[4 6]
[3 7]


In [13]:
arr=np.array([10,23,43,97,65,20,30,40,50])

print(arr[arr>20])

[23 43 97 65 30 40 50]


In [14]:
print(arr[arr % 2 == 0])

[10 20 30 40 50]
