In [1]:
import numpy as np 
marks=np.array([[85,78,90],[70,88,60],[95,92,89]])
print("Average:",np.mean(marks))
print("Highest:",np.max(marks))
print("Lowest:",np.min(marks))

Average: 83.0
Highest: 95
Lowest: 60


In [3]:
total=np.sum(marks,axis=1)
print(total)
top_student=np.argmax(total)
print("Top student index:",top_student)

[253 218 276]
Top student index: 2


In [4]:
image=np.array([[255,0,0],[0,255,0],[0,0,255]])
brightness=image+50
print("Brightness adjusted image:\n",brightness)

Brightness adjusted image:
 [[305  50  50]
 [ 50 305  50]
 [ 50  50 305]]


In [5]:
image=np.array([[255,0,0],[0,255,0],[0,0,255]])
brightness=image-50
print("Brightness adjusted image:\n",brightness)

Brightness adjusted image:
 [[205 -50 -50]
 [-50 205 -50]
 [-50 -50 205]]


In [6]:
data=np.array([10,20,30,40,50])
normalized=data/np.max(data)
print("Normalized data:",normalized)

Normalized data: [0.2 0.4 0.6 0.8 1. ]


In [12]:
arr1=np.array([100,27,63,94,55,90])
reshape=arr1.reshape(2,3)
print("Reshaped array:\n",reshape)

Reshaped array:
 [[100  27  63]
 [ 94  55  90]]


In [14]:
arr2=np.array([[1,2],[3,4]])
reshape=arr2.reshape(4)
print("Reshaped array:\n",reshape)

Reshaped array:
 [1 2 3 4]


In [15]:
arr3=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Original array:\n",arr3)

Original array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [8]:
arr=np.array([100,27,63,94,55])
filter=arr[arr>50]
replace=arr[arr<50]
print("Filtered array:",filter)
print("Replaced array:",replace)
print(len(filter))

Filtered array: [100  63  94  55]
Replaced array: [27]
4


In [16]:
attendance=np.array([[1,0,1],[0,1,1],[1,1,0]])
print("Original attendance:\n",attendance)

Original attendance:
 [[1 0 1]
 [0 1 1]
 [1 1 0]]


In [17]:
marks = np.array([
    [85, 90, 78],
    [88, 76, 95],
    [92, 89, 80]
])

print(marks)

[[85 90 78]
 [88 76 95]
 [92 89 80]]


In [ ]:
weather = np.array([
    [32, 70],   
    [30, 65],   
    [31, 80]    
])

print(weather)

[[32 70]
 [30 65]
 [31 80]]
