In [3]:
import numpy as np
arr=np.array([10,70,40,60,20])
print(arr[0])
print(arr[-1])
print(arr[1:4])

10
20
[70 40 60]


In [7]:
arr2=np.array([[10,20,30],[40,50,60],[70,800,90]])
print(arr2[0,1])
print(arr2[0])
print(arr2[1])
print(arr2[:,1])

20
[10 20 30]
[40 50 60]
[ 20  50 800]


In [9]:
arr2=np.array([[[10,20,30],[40,50,60]],[[70,800,90],[100,110,120]],[[130,140,150],[160,170,180]]])
print(arr2[0])
print(arr2[0][1])
print(arr2[0][1][2])

[[10 20 30]
 [40 50 60]]
[40 50 60]
60


In [10]:
import numpy as np
arr=np.array([10,20,30,40,50])
sub_arr=arr[1:4]
print(sub_arr)

[20 30 40]


In [11]:
arr=np.array([10,40,80,60,30])
print(arr[::2])

[10 80 30]


In [ ]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
rows=arr[0:2,:]
cols=arr[:,0:2]
print(rows)
print(cols)


[[10 20 30]
 [40 50 60]]
[[10 20]
 [40 50]
 [70 80]]


In [14]:
arr=np.array([10,50,90,70,40,30])
print(arr[arr>25])
print(arr[(arr>50) & (arr<90)])

[50 90 70 40 30]
[70]


In [15]:
arr = np.array([10, 20, 30, 40, 50])
arr[arr > 25] = 0
print(arr)

[10 20  0  0  0]
