In [2]:
import numpy as np
print(np.random.randint(1,10))

2


In [7]:
arr=np.array([1,2,3,4,5,6])
A=np.random.randint(0,10,(3,3))
print(A)

[[0 5 1]
 [1 9 4]
 [4 0 5]]


In [5]:
print(np.random.rand(3))
print(np.random.rand(3,3))

[0.61948794 0.38398682 0.9394473 ]
[[0.0509207  0.74663259 0.74790113]
 [0.86372914 0.02538565 0.03707114]
 [0.47681117 0.36911218 0.69403133]]


In [9]:
color=['red','blue','green','yellow']
print(np.random.choice(color))
print(np.random.choice(color,size=5))

blue
['blue' 'red' 'blue' 'yellow' 'green']


In [14]:
a=np.random.randint(0,256)
print(a)

162


In [12]:
arr=np.array([1,2,3,4,5,6])
shuffle=np.random.shuffle(arr)
print(arr)

[5 4 2 1 6 3]


In [13]:
student_id=np.array([1,2,3,4,5])
shuffle_id=np.random.shuffle(student_id)
print(student_id)

[1 4 5 2 3]


In [16]:
marks=np.array([[80,90,85],[75,80,70],[90,95,92]])
print("mark dataset")
print(marks)

mark dataset
[[80 90 85]
 [75 80 70]
 [90 95 92]]


In [17]:
attendance=np.array([[1,0,1],[1,1,0],[0,1,1]])
print("attendance dataset")
print(attendance)

attendance dataset
[[1 0 1]
 [1 1 0]
 [0 1 1]]


In [18]:
image=np.random.randint(0,256,size=(5,5,3))
print("image dataset")
print(image)

image dataset
[[[118  95 231]
  [ 54  96   5]
  [ 64 148  82]
  [133 183 211]
  [ 16 106 253]]

 [[  8 129  99]
  [116 245  82]
  [177 239 173]
  [220 150 251]
  [ 25  87 255]]

 [[178 238  79]
  [137  74  93]
  [243 206 224]
  [144  30 166]
  [152 250 215]]

 [[217 138 138]
  [224 191  72]
  [180  50 239]
  [ 23 161 221]
  [249 154 237]]

 [[  4 185 145]
  [ 67  26 185]
  [ 72 103  81]
  [198  58  93]
  [123  53  16]]]
