In [2]:
import numpy as np
arr1=np.array([1,2,3,4])

In [3]:
arr2=np.array([[1,2],[3,4]])
arr3=np.array([[[1,2],[3,4]]])

In [4]:
print(arr1)
print(arr2)
print(arr3)

[1 2 3 4]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]]


In [5]:
print(arr1.shape)
print(arr2.ndim)
print(arr3.dtype)

(4,)
2
int64


In [6]:
np.zeros((2,3))
np.ones((3,4))
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [8]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr=np.array([1,2,3,4,5,6])
print(arr[0])
print(arr[1:4])

1
[2 3 4]


In [13]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[0,1])

2


In [14]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
arr2=arr1.reshape(2,5)
print(arr2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [16]:
arr2=np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr1=arr2.reshape(-1)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]
