In [2]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

150
30.0
50
10


In [7]:
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(arr2,axis=1))
print(np.sum(arr2,axis=0))

30.0
14.142135623730951
200.0
[ 6 15 24]
[12 15 18]


In [8]:
print(np.mean(arr2,axis=1))

[2. 5. 8.]


In [9]:
print(np.argmax(arr2))
print(np.argmin(arr2))

8
0


In [10]:
arr=np.array([1,2,3,4])
print(np.cumsum(arr))

[ 1  3  6 10]
