In [1]:
import numpy as np
arr=np.array([10,20,30,40,50])
add=arr+5
print(add)
mul=arr*5
print(mul)
div=arr/5
print(div)

[15 25 35 45 55]
[ 50 100 150 200 250]
[ 2.  4.  6.  8. 10.]


In [2]:
import numpy as np
a=np.array([[1],[2],[3],[4]])
b=np.array([1,2,3,4])
print(a+b)
print(a*b)

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [3]:
print(a.shape)
print(b.shape)

(4, 1)
(4,)


In [6]:
arr = np.array([
 [1, 2, 3],
 [4, 5, 6]
])
print(arr + 100)
print(arr * 2)
normalized=arr / np.max(arr)
print(normalized)

[[101 102 103]
 [104 105 106]]
[[ 2  4  6]
 [ 8 10 12]]
[[0.16666667 0.33333333 0.5       ]
 [0.66666667 0.83333333 1.        ]]
